/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AuthAalLevel = 'aal1' | 'aal2' | 'aal3';

export type AuthCodeChallengeMethod = 'plain' | 's256';

export type AuthFactorStatus = 'unverified' | 'verified';

export type AuthFactorType = 'phone' | 'totp' | 'webauthn';

export type AuthOauthAuthorizationStatus = 'approved' | 'denied' | 'expired' | 'pending';

export type AuthOauthClientType = 'confidential' | 'public';

export type AuthOauthRegistrationType = 'dynamic' | 'manual';

export type AuthOauthResponseType = 'code';

export type AuthOneTimeTokenType =
  | 'confirmation_token'
  | 'email_change_token_current'
  | 'email_change_token_new'
  | 'phone_change_token'
  | 'reauthentication_token'
  | 'recovery_token';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type StorageBuckettype = 'ANALYTICS' | 'STANDARD' | 'VECTOR';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accountCreatedTime: Generated<Timestamp>;
  accountDeletedTime: Timestamp | null;
  accountId: Generated<string>;
  accountProvider: string;
  accountProviderUserId: string;
  accountType: string;
  accountUpdatedTime: Timestamp | null;
  accountUserId: string;
}

export interface Attachment {
  attachmentCreatedTime: Generated<Timestamp>;
  attachmentDeletedTime: Timestamp | null;
  attachmentHeight: Int8 | null;
  attachmentId: Generated<string>;
  attachmentMimetype: string;
  attachmentName: string;
  attachmentOwnerId: string | null;
  attachmentPath: string;
  attachmentSize: Int8;
  attachmentUpdatedTime: Timestamp | null;
  attachmentWidth: Int8 | null;
}

export interface AuthAuditLogEntries {
  createdAt: Timestamp | null;
  id: string;
  instanceId: string | null;
  ipAddress: Generated<string>;
  payload: Json | null;
}

export interface AuthFlowState {
  authCode: string;
  authCodeIssuedAt: Timestamp | null;
  authenticationMethod: string;
  codeChallenge: string;
  codeChallengeMethod: AuthCodeChallengeMethod;
  createdAt: Timestamp | null;
  id: string;
  providerAccessToken: string | null;
  providerRefreshToken: string | null;
  providerType: string;
  updatedAt: Timestamp | null;
  userId: string | null;
}

export interface AuthIdentities {
  createdAt: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identityData: Json;
  lastSignInAt: Timestamp | null;
  provider: string;
  providerId: string;
  updatedAt: Timestamp | null;
  userId: string;
}

export interface AuthInstances {
  createdAt: Timestamp | null;
  id: string;
  rawBaseConfig: string | null;
  updatedAt: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authenticationMethod: string;
  createdAt: Timestamp;
  id: string;
  sessionId: string;
  updatedAt: Timestamp;
}

export interface AuthMfaChallenges {
  createdAt: Timestamp;
  factorId: string;
  id: string;
  ipAddress: string;
  otpCode: string | null;
  verifiedAt: Timestamp | null;
  webAuthnSessionData: Json | null;
}

export interface AuthMfaFactors {
  createdAt: Timestamp;
  factorType: AuthFactorType;
  friendlyName: string | null;
  id: string;
  lastChallengedAt: Timestamp | null;
  /**
   * Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
   */
  lastWebauthnChallengeData: Json | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updatedAt: Timestamp;
  userId: string;
  webAuthnAaguid: string | null;
  webAuthnCredential: Json | null;
}

export interface AuthOauthAuthorizations {
  approvedAt: Timestamp | null;
  authorizationCode: string | null;
  authorizationId: string;
  clientId: string;
  codeChallenge: string | null;
  codeChallengeMethod: AuthCodeChallengeMethod | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Generated<Timestamp>;
  id: string;
  nonce: string | null;
  redirectUri: string;
  resource: string | null;
  responseType: Generated<AuthOauthResponseType>;
  scope: string;
  state: string | null;
  status: Generated<AuthOauthAuthorizationStatus>;
  userId: string | null;
}

export interface AuthOauthClients {
  clientName: string | null;
  clientSecretHash: string | null;
  clientType: Generated<AuthOauthClientType>;
  clientUri: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  grantTypes: string;
  id: string;
  logoUri: string | null;
  redirectUris: string;
  registrationType: AuthOauthRegistrationType;
  updatedAt: Generated<Timestamp>;
}

export interface AuthOauthConsents {
  clientId: string;
  grantedAt: Generated<Timestamp>;
  id: string;
  revokedAt: Timestamp | null;
  scopes: string;
  userId: string;
}

export interface AuthOneTimeTokens {
  createdAt: Generated<Timestamp>;
  id: string;
  relatesTo: string;
  tokenHash: string;
  tokenType: AuthOneTimeTokenType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AuthRefreshTokens {
  createdAt: Timestamp | null;
  id: Generated<Int8>;
  instanceId: string | null;
  parent: string | null;
  revoked: boolean | null;
  sessionId: string | null;
  token: string | null;
  updatedAt: Timestamp | null;
  userId: string | null;
}

export interface AuthSamlProviders {
  attributeMapping: Json | null;
  createdAt: Timestamp | null;
  entityId: string;
  id: string;
  metadataUrl: string | null;
  metadataXml: string;
  nameIdFormat: string | null;
  ssoProviderId: string;
  updatedAt: Timestamp | null;
}

export interface AuthSamlRelayStates {
  createdAt: Timestamp | null;
  flowStateId: string | null;
  forEmail: string | null;
  id: string;
  redirectTo: string | null;
  requestId: string;
  ssoProviderId: string;
  updatedAt: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  createdAt: Timestamp | null;
  factorId: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  notAfter: Timestamp | null;
  oauthClientId: string | null;
  refreshedAt: Timestamp | null;
  /**
   * Holds the ID (counter) of the last issued refresh token.
   */
  refreshTokenCounter: Int8 | null;
  /**
   * Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
   */
  refreshTokenHmacKey: string | null;
  scopes: string | null;
  tag: string | null;
  updatedAt: Timestamp | null;
  userAgent: string | null;
  userId: string;
}

export interface AuthSsoDomains {
  createdAt: Timestamp | null;
  domain: string;
  id: string;
  ssoProviderId: string;
  updatedAt: Timestamp | null;
}

export interface AuthSsoProviders {
  createdAt: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resourceId: string | null;
  updatedAt: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  bannedUntil: Timestamp | null;
  confirmationSentAt: Timestamp | null;
  confirmationToken: string | null;
  confirmedAt: Generated<Timestamp | null>;
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  email: string | null;
  emailChange: string | null;
  emailChangeConfirmStatus: Generated<number | null>;
  emailChangeSentAt: Timestamp | null;
  emailChangeTokenCurrent: Generated<string | null>;
  emailChangeTokenNew: string | null;
  emailConfirmedAt: Timestamp | null;
  encryptedPassword: string | null;
  id: string;
  instanceId: string | null;
  invitedAt: Timestamp | null;
  isAnonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  isSsoUser: Generated<boolean>;
  isSuperAdmin: boolean | null;
  lastSignInAt: Timestamp | null;
  phone: Generated<string | null>;
  phoneChange: Generated<string | null>;
  phoneChangeSentAt: Timestamp | null;
  phoneChangeToken: Generated<string | null>;
  phoneConfirmedAt: Timestamp | null;
  rawAppMetaData: Json | null;
  rawUserMetaData: Json | null;
  reauthenticationSentAt: Timestamp | null;
  reauthenticationToken: Generated<string | null>;
  recoverySentAt: Timestamp | null;
  recoveryToken: string | null;
  role: string | null;
  updatedAt: Timestamp | null;
}

export interface Domain {
  domainCreatedTime: Generated<Timestamp>;
  domainDeletedTime: Timestamp | null;
  domainId: Generated<string>;
  domainName: string;
  domainUpdatedTime: Timestamp | null;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jitDeformCount: Int8 | null;
  jitDeformTime: number | null;
  jitEmissionCount: Int8 | null;
  jitEmissionTime: number | null;
  jitFunctions: Int8 | null;
  jitGenerationTime: number | null;
  jitInliningCount: Int8 | null;
  jitInliningTime: number | null;
  jitOptimizationCount: Int8 | null;
  jitOptimizationTime: number | null;
  localBlkReadTime: number | null;
  localBlksDirtied: Int8 | null;
  localBlksHit: Int8 | null;
  localBlksRead: Int8 | null;
  localBlksWritten: Int8 | null;
  localBlkWriteTime: number | null;
  maxExecTime: number | null;
  maxPlanTime: number | null;
  meanExecTime: number | null;
  meanPlanTime: number | null;
  minExecTime: number | null;
  minmaxStatsSince: Timestamp | null;
  minPlanTime: number | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  sharedBlkReadTime: number | null;
  sharedBlksDirtied: Int8 | null;
  sharedBlksHit: Int8 | null;
  sharedBlksRead: Int8 | null;
  sharedBlksWritten: Int8 | null;
  sharedBlkWriteTime: number | null;
  statsSince: Timestamp | null;
  stddevExecTime: number | null;
  stddevPlanTime: number | null;
  tempBlkReadTime: number | null;
  tempBlksRead: Int8 | null;
  tempBlksWritten: Int8 | null;
  tempBlkWriteTime: number | null;
  toplevel: boolean | null;
  totalExecTime: number | null;
  totalPlanTime: number | null;
  userid: number | null;
  walBytes: Numeric | null;
  walFpi: Int8 | null;
  walRecords: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  statsReset: Timestamp | null;
}

export interface Interest {
  interestCreatedTime: Generated<Timestamp>;
  interestDeletedTime: Timestamp | null;
  interestId: Generated<string>;
  interestName: string;
  interestPosition: Numeric;
  interestUpdatedTime: Timestamp | null;
}

export interface PersonalGoal {
  personalGoalCreatedTime: Generated<Timestamp>;
  personalGoalDeletedTime: Timestamp | null;
  personalGoalDescription: string | null;
  personalGoalId: Generated<string>;
  personalGoalName: string;
  personalGoalPosition: Numeric;
  personalGoalTitle: string;
  personalGoalUpdatedTime: Timestamp | null;
}

export interface Pronoun {
  pronounCreatedTime: Generated<Timestamp>;
  pronounDeletedTime: Timestamp | null;
  pronounId: Generated<string>;
  pronounName: string;
  pronounUpdatedTime: Timestamp | null;
}

export interface RealtimeMessages {
  event: string | null;
  extension: string;
  id: Generated<string>;
  insertedAt: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updatedAt: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  insertedAt: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  claims: Json;
  claimsRole: Generated<string>;
  createdAt: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  subscriptionId: string;
}

export interface Role {
  roleCreatedTime: Generated<Timestamp>;
  roleDeletedTime: Timestamp | null;
  roleId: Generated<string>;
  roleName: string;
  roleRank: Int8;
  roleUpdatedTime: Timestamp | null;
}

export interface StorageBuckets {
  allowedMimeTypes: string[] | null;
  avifAutodetection: Generated<boolean | null>;
  createdAt: Generated<Timestamp | null>;
  fileSizeLimit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  ownerId: string | null;
  public: Generated<boolean | null>;
  type: Generated<StorageBuckettype>;
  updatedAt: Generated<Timestamp | null>;
}

export interface StorageBucketsAnalytics {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  format: Generated<string>;
  id: Generated<string>;
  name: string;
  type: Generated<StorageBuckettype>;
  updatedAt: Generated<Timestamp>;
}

export interface StorageBucketsVectors {
  createdAt: Generated<Timestamp>;
  id: string;
  type: Generated<StorageBuckettype>;
  updatedAt: Generated<Timestamp>;
}

export interface StorageMigrations {
  executedAt: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  bucketId: string | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<string>;
  lastAccessedAt: Generated<Timestamp | null>;
  level: number | null;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  ownerId: string | null;
  pathTokens: Generated<string[] | null>;
  updatedAt: Generated<Timestamp | null>;
  userMetadata: Json | null;
  version: string | null;
}

export interface StoragePrefixes {
  bucketId: string;
  createdAt: Generated<Timestamp | null>;
  level: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface StorageS3MultipartUploads {
  bucketId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  inProgressSize: Generated<Int8>;
  key: string;
  ownerId: string | null;
  uploadSignature: string;
  userMetadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucketId: string;
  createdAt: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  ownerId: string | null;
  partNumber: number;
  size: Generated<Int8>;
  uploadId: string;
  version: string;
}

export interface StorageVectorIndexes {
  bucketId: string;
  createdAt: Generated<Timestamp>;
  dataType: string;
  dimension: number;
  distanceMetric: string;
  id: Generated<string>;
  metadataConfiguration: Json | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface University {
  universityCountry: string;
  universityCreatedTime: Generated<Timestamp>;
  universityDeletedTime: Timestamp | null;
  universityId: Generated<string>;
  universityName: string;
  universityUpdatedTime: Timestamp | null;
}

export interface User {
  userAvatarUrl: string;
  userCreatedTime: Generated<Timestamp>;
  userDeletedTime: Timestamp | null;
  userDisplayName: string;
  userDisplayNameTsv: string | null;
  userEmail: string;
  userId: Generated<string>;
  userLastSignedTime: Timestamp;
  userPasswordHash: string | null;
  userRoleId: string | null;
  userUpdatedTime: Timestamp | null;
}

export interface UserInfo {
  userInfoBio: string | null;
  userInfoCreatedTime: Generated<Timestamp>;
  userInfoDeletedTime: Timestamp | null;
  userInfoDomainId: string | null;
  userInfoId: Generated<string>;
  userInfoLookingFor: string | null;
  userInfoPronounId: string | null;
  userInfoUniversityId: string | null;
  userInfoUpdatedTime: Timestamp | null;
  userInfoUserId: string;
}

export interface UserInfoInterest {
  userInfoInterestCreatedTime: Generated<Timestamp>;
  userInfoInterestId: Generated<string>;
  userInfoInterestInterestId: string;
  userInfoInterestPosition: Numeric;
  userInfoInterestUpdatedTime: Timestamp | null;
  userInfoInterestUserInfoId: string;
}

export interface UserInfoPersonalGoal {
  userInfoPersonalGoalCreatedTime: Generated<Timestamp>;
  userInfoPersonalGoalId: Generated<string>;
  userInfoPersonalGoalPersonalGoalId: string;
  userInfoPersonalGoalPosition: Numeric;
  userInfoPersonalGoalUpdatedTime: Timestamp | null;
  userInfoPersonalGoalUserInfoId: string;
}

export interface UserToken {
  userTokenCreatedTime: Generated<Timestamp>;
  userTokenExpiredTime: Timestamp;
  userTokenId: Generated<string>;
  userTokenTokenHash: string;
  userTokenType: string;
  userTokenUsedTime: Timestamp | null;
  userTokenUserId: string;
}

export interface VaultDecryptedSecrets {
  createdAt: Timestamp | null;
  decryptedSecret: string | null;
  description: string | null;
  id: string | null;
  keyId: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updatedAt: Timestamp | null;
}

export interface VaultSecrets {
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  keyId: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  account: Account;
  attachment: Attachment;
  'auth.auditLogEntries': AuthAuditLogEntries;
  'auth.flowState': AuthFlowState;
  'auth.identities': AuthIdentities;
  'auth.instances': AuthInstances;
  'auth.mfaAmrClaims': AuthMfaAmrClaims;
  'auth.mfaChallenges': AuthMfaChallenges;
  'auth.mfaFactors': AuthMfaFactors;
  'auth.oauthAuthorizations': AuthOauthAuthorizations;
  'auth.oauthClients': AuthOauthClients;
  'auth.oauthConsents': AuthOauthConsents;
  'auth.oneTimeTokens': AuthOneTimeTokens;
  'auth.refreshTokens': AuthRefreshTokens;
  'auth.samlProviders': AuthSamlProviders;
  'auth.samlRelayStates': AuthSamlRelayStates;
  'auth.schemaMigrations': AuthSchemaMigrations;
  'auth.sessions': AuthSessions;
  'auth.ssoDomains': AuthSsoDomains;
  'auth.ssoProviders': AuthSsoProviders;
  'auth.users': AuthUsers;
  domain: Domain;
  'extensions.pgStatStatements': ExtensionsPgStatStatements;
  'extensions.pgStatStatementsInfo': ExtensionsPgStatStatementsInfo;
  interest: Interest;
  personalGoal: PersonalGoal;
  pronoun: Pronoun;
  'realtime.messages': RealtimeMessages;
  'realtime.schemaMigrations': RealtimeSchemaMigrations;
  'realtime.subscription': RealtimeSubscription;
  role: Role;
  'storage.buckets': StorageBuckets;
  'storage.bucketsAnalytics': StorageBucketsAnalytics;
  'storage.bucketsVectors': StorageBucketsVectors;
  'storage.migrations': StorageMigrations;
  'storage.objects': StorageObjects;
  'storage.prefixes': StoragePrefixes;
  'storage.s3MultipartUploads': StorageS3MultipartUploads;
  'storage.s3MultipartUploadsParts': StorageS3MultipartUploadsParts;
  'storage.vectorIndexes': StorageVectorIndexes;
  university: University;
  user: User;
  userInfo: UserInfo;
  userInfoInterest: UserInfoInterest;
  userInfoPersonalGoal: UserInfoPersonalGoal;
  userToken: UserToken;
  'vault.decryptedSecrets': VaultDecryptedSecrets;
  'vault.secrets': VaultSecrets;
}
